server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # SPA routing: serve index.html per qualsiasi rotta non trovata come file
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Evita di loggare richieste favicon/robots
    location = /favicon.ico { log_not_found off; access_log off; }
    location = /robots.txt  { log_not_found off; access_log off; }
}
